name: AE2-PBR-1.21
description: PBR for Applied Energistics 2 [1.21.1]
author: Joshua Miller
input:
  format: raw
profiles:
- edition: Java
  format: 15
  name: AE2-LabPbr
  description: ''
  encoding:
    format: lab-1.3
  texture-size: 16
- edition: Java
  format: 15
  name: AE2-OldPbr
  description: ''
  encoding:
    format: old-pbr
  texture-size: 16
