name: AE2-PBR
input:
  format: raw
profiles:
- edition: Java
  format: 15
  name: AE2-LabPbr
  description: LAB-PBR
  encoding:
    format: lab-1.3
  texture-size: 16
- edition: Java
  format: 15
  name: AE2-OldPbr
  description: OLD-PBR
  encoding:
    format: old-pbr
  texture-size: 16
