name: Release
on: workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile LabPBR 1.20
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-1.20/project.yml
          profile: AE2-LabPBR
          zip: AE2-1.20-LabPBR-v${{ github.run_number }}.zip
      - name: Compile OldPBR 1.20
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-1.20/project.yml
          profile: AE2-OldPBR
          zip: AE2-1.20-OldPBR-v${{ github.run_number }}.zip
      - name: Compile LabPBR 1.21
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-1.21/project.yml
          profile: AE2-LabPBR
          zip: AE2-1.21-LabPBR-v${{ github.run_number }}.zip
      - name: Compile OldPBR 1.21
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-1.21/project.yml
          profile: AE2-OldPBR
          zip: AE2-1.21-OldPBR-v${{ github.run_number }}.zip
      - name: Publish 1.20 to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: AE2-PBR v${{ github.run_number }} for 1.20
          version: v${{ github.run_number }}-1.20
          version-type: beta
          changelog: "TODO"
          loaders: |
            fabric
            forge
            quilt
          files: |
            AE2-1.20-LabPBR-v${{ github.run_number }}.zip
            AE2-1.20-OldPBR-v${{ github.run_number }}.zip
          game-versions: '1.20.1'
          game-version-filter: none
          modrinth-id: 5x1MHOKX
          modrinth-featured: true
          modrinth-loaders: minecraft
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          dependencies: |
            ae2(optional){modrinth:XxWD5pD3}
      - name: Publish 1.21 to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: AE2-PBR v${{ github.run_number }} for 1.21
          version: v${{ github.run_number }}-1.21
          version-type: beta
          changelog: "TODO"
          loaders: |
            fabric
            forge
            quilt
          files: |
            AE2-1.21-LabPBR-v${{ github.run_number }}.zip
            AE2-1.21-OldPBR-v${{ github.run_number }}.zip
          game-versions: '1.21.1'
          game-version-filter: none
          modrinth-id: 5x1MHOKX
          modrinth-featured: true
          modrinth-loaders: minecraft
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          dependencies: |
            ae2(optional){modrinth:XxWD5pD3}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: TODO
          draft: true
          prerelease: true
          tag_name: v${{ github.run_number }}
          files: |
            AE2-1.20-LabPBR-v${{ github.run_number }}.zip
            AE2-1.20-OldPBR-v${{ github.run_number }}.zip
            AE2-1.21-LabPBR-v${{ github.run_number }}.zip
            AE2-1.21-OldPBR-v${{ github.run_number }}.zip
