name: Release
on: workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile LabPBR
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: AE2-LabPBR
          zip: AE2-LabPBR-v${{ github.run_number }}.zip
      - name: Compile OldPBR
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: AE2-OldPBR
          zip: AE2-OldPBR-v${{ github.run_number }}.zip
      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: AE2-PBR v${{ github.run_number }}
          version: v${{ github.run_number }}
          version-type: beta
          changelog: "TODO"
          loaders: |
            fabric
            forge
            quilt
          files: |
            AE2-LabPBR-v${{ github.run_number }}.zip
            AE2-OldPBR-v${{ github.run_number }}.zip
          game-versions: '>=1.16'
          game-version-filter: none
          modrinth-id: 5x1MHOKX
          modrinth-featured: true
          modrinth-loaders: minecraft
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-draft: true
          github-prerelease: true
          github-tag: v${{ github.run_number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dependencies: |
            ae2(optional){modrinth:XxWD5pD3}
